# Generated by Django 3.2.9 on 2022-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_resturantbranch_resturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantbranch',
            name='sub_domain',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
