# Generated by Django 3.2.9 on 2022-07-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_resturantbranch_sub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='brnanch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.resturantbranch'),
        ),
    ]
