# Generated by Django 3.2.9 on 2022-07-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_account_brnanch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantbranch',
            name='resturant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.resturant'),
        ),
    ]
