# Generated by Django 3.2.9 on 2022-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_resturantbranch_resturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantbranch',
            name='main_domain',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
